### PR TITLE
Drop PMO specific parameters from config create command

### PR DESCRIPTION
**Pull request by pshanbhag**
While setting up the config, there are a bunch of DNS, hostname related commands
requested from the user. These fields are mandatory and will be prompted for
when the config create command is run. These options don't make much sense to be
asked in the PMK context. This change drops the prompts/mandatory property for
these optional parameters.

This is a quick workaround and not necessarily the right long term fix. But with
the immediate priority on PMK, putting this in place till we figure out the
right long term solution

### CODE REVIEW

**Comment by pshanbhag** [comment]
Looking into fixing the test failure.

**Comment by pshanbhag** [comment]
@tomchris, is there a way to retrigger this test here? The tests are actually passing on my dev box. So I don't know how to figure this test failure out?

**Comment by tomchris** [comment]
@pshanbhag Commit your changes and push your code to this branch again. The test will be triggered automatically.

**Comment by pshanbhag** [comment]
Fixed the issue. Unfortunately, I had to move away from command option callbacks. Again a quick solution instead of possibly the right long term solution.

**Pull request merged**
